import Navbar from "@/component/Navbar/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import AuthProvider from "@/context/auth";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar/> 
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
